### ISSUE TITLE
安装entware结束后再次运行  报错

### ISSUE THREAD

**Issue by xjbeta** [houzi-/dd-wrt-shadowsocks#1]
jffs格式化后

mkdir /jffs/opt
mount -o bind /jffs/opt /opt

![4768fbef2291e2996f34d160c2b1a962.jpg](http://moefq.com/images/2016/06/07/4768fbef2291e2996f34d160c2b1a962.jpg)

**Comment by xjbeta** [comment]
之后再次运行/tmp/shadowsocks -su
![6d35b12327a2c3d684db0136cbb4c28f.jpg](http://moefq.com/images/2016/06/07/6d35b12327a2c3d684db0136cbb4c28f.jpg)

**Comment by houzi-** [comment]
我帮你远程看一下吧！直接email给我，我在这里不方便提供联系信息

xjbeta notifications@github.com于2016年6月7日周二 10:43写道：

> 之后再次运行/tmp/shadowsocks -su
> [image: 6d35b12327a2c3d684db0136cbb4c28f.jpg]
> https://camo.githubusercontent.com/f4b5dee7f8f3b7658b0b1b274851ceb95997866f/687474703a2f2f6d6f6566712e636f6d2f696d616765732f323031362f30362f30372f36643335623132333237613263336436383464623031333663626234633238662e6a7067
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/houzi-/dd-wrt-shadowsocks/issues/1#issuecomment-224152508,
> or mute the thread
> https://github.com/notifications/unsubscribe/AI9fG-wuyWw4RSP0_Ll422Mfjp39I8SKks5qJNq8gaJpZM4Ivf6w
> .
> 
> ## 

JasonLin

**Comment by xjbeta** [comment]
总算搞明白怎么装了   我去重新整理整理你的教程。。。。

**Comment by houzi-** [comment]
不知道你的问题解决了没？

**Comment by xjbeta** [comment]
shadowsocks -g  全局可以  -S没用 : ]

**Comment by houzi-** [comment]
可能你配置的问题喽！你加过我企鹅🐧吗？

**Comment by xjbeta** [comment]
有验证问题。。。

**Comment by houzi-** [comment]
问题:maybe

xjbeta notifications@github.com于2016年6月12日周日 17:21写道：

> 有验证问题。。。
> 
> —
> You are receiving this because you commented.
> 
> Reply to this email directly, view it on GitHub
> https://github.com/houzi-/dd-wrt-shadowsocks/issues/1#issuecomment-225421160,
> or mute the thread
> https://github.com/notifications/unsubscribe/AI9fG628WGryTqcFM0nfOL5LPUMCq_5pks5qK8-AgaJpZM4Ivf6w
> .
> 
> ## 

JasonLin
