### ISSUE TITLE
DLINK DIR-868L无法使用，无法解析客户端dns，qq可以上，网页打不开，重装必须重置路由器

### ISSUE THREAD

**Issue by hmgl** [houzi-/dd-wrt-shadowsocks#2]
DLINK DIR-868L无法使用，5种方案均无法解析客户端dns，qq可以上，网页打不开，重装必须重置路由器。以前的有个老版本可以用，但是不稳定

**Comment by houzi-** [comment]
https://github.com/houzi-/dd-wrt-shadowsocks#support
