### ISSUE TITLE
请问有没有支持R6300v1版本的包

### ISSUE THREAD

**Issue by alex8224** [houzi-/dd-wrt-shadowsocks#3]
你好，
我的是Netgear R6300v1,使用你这个包貌似用不了.请问有没有支持的包
谢谢.

**Comment by houzi-** [comment]
不支持mipsel的

2016-07-18 18:22 GMT+08:00 Alexzhang notifications@github.com:

**Comment by alex8224** [comment]
下面的能不能用?
http://pan.baidu.com/share/link?shareid=2120898701&uk=3658832225#path=%252Fpackages%252Fmipsel%2520packages%252FV5.0-mipselsf(entware-ng)%252Fstatic

hackshell notifications@github.com于2016年7月18日周一 下午6:23写道：
