### ISSUE TITLE
r6300v2，安装总出错

### ISSUE THREAD

**Issue by jackma66** [houzi-/dd-wrt-shadowsocks#4]
你好，下面是终端显示的一些信息，先安装了entware的。
- opkg_install_cmd: Cannot install package entware-opt.
  Info: Congratulations! I
  nfo: If there are no errors above then Entware-ng was successfully initialized.
  Info: Add /opt/bin & /opt/sbin to your PATH variable 
  Info: Add '/opt/etc/init.d/rc.unslung start' to startup script for Entware-ng services to start 
  Info: Found a Bug? Please report at https://github.com/Entware-ng/Entware-ng/issues 
  Info: Found a mirror bug? Please report at https://github.com/flzyup/entwaremirror Info: Or send mail to: yonnie.lu.inc@gmail.com 
  You do not import the entire IPK!
  运行 /tmp/shadowsocks -su ，安装不了，再次运行会删除整个opt文件夹。确认7个要求的ipk都上传了的，试了一天没试出个结果来。

**Comment by houzi-** [comment]
部署脚本的版本号是多少？编辑日期？

**Comment by jackma66** [comment]
Latest release
 V1.4-3-stable
armv7_shadowsocks.zip
只用了这个。

**Comment by houzi-** [comment]
脚本跟版本号跟固件的发布日期是对应的，最新的固件得使用最新的脚本

**Comment by jackma66** [comment]
早。
谢谢，换了最新脚本通过了，但出现新的问题，shadowsocks 账号验证不通过。
WARNING:  You input an incorrect IP, please re-enter your: shadowsocks -su
换了两个ip都没效果

在安装之前自定义了shadowsocks.json里面的账户，不知道跟这个有没有关系

**Comment by houzi-** [comment]
你找一个能ping通的账号，让其部署成功后，再修改成有些ping不通的账号

**Comment by houzi-** [comment]
如果确认账号能ping通，那就再多执行几次-u命令，这个是没有影响的，因为你的主体已经部署成功了，只需要录入账号和选择方案

**Comment by jackma66** [comment]
INFO:  Please select Please choose the following programs:
##programs_1##: (ss-redir+gfwlist+pdnsd)
##programs_2##: (ss-redir+chnroutes+chinadns+pdnsd)
##programs_3##: (ss-redir+chnroutes+chinadns+dnscrypt-proxy)
##programs_4##: (ss-redir+chnroutes+pcap_dnsproxy)
##programs_5##: (ss-tunnel+chnroutes+chinadns)
Your Choice:
programs_3

方案的选择是否输入“programs_num”？我输入了programs_3，再restart shadowsocks

现在碰到的问题是：
root@DD-WRT:/opt# ./shadowsocks -sa start
 **WARNING** USE AT YOUR OWN RISK! You want to start all service under /opt/etc/init.d?(y/N)
y
cp: can't stat '/opt/etc/dnsmasq.conf.bak': No such file or directory
iptables-restore: line 69 failed
 Flush_iptables...              done.
 Starting ss-local...              done.
 Starting ss-watchdog...              done.
 Loading iptables rules...              done.

没有dnsmasq.conf.bak，/tmp/ 里面倒是有一个dnsmasq.conf，能把它改名复制了放进/opt/etc/ 吗？
现在的情况是用chrome switchomega插件配合测试可用，关了插件就用不了了。

ipset -L 
root@DD-WRT:/opt/etc# ipset -L
-sh: ipset: not found

entware里有个ipset4的，安装过后再输入
root@DD-WRT:/opt/etc# ipset -L
ipset v4.5: Kernel ip_set module is of protocol version 6.I'm of protocol version 4.
Please upgrade your kernel and/or ipset(8) utillity.

想自己解决问题（要先看懂您的脚本），这方面的知识要看什么文档呢？感觉浪费了大量时间，但实践中对几个命令的用法倒是熟悉了很多。谢谢你。

**Comment by houzi-** [comment]
这个脚本只适用我提供的DD-WRT固件，如果你使用的是KONG/BS的就是不支持的

**Comment by houzi-** [comment]
选择方案是直接输入数字3就可以

**Comment by houzi-** [comment]
认真看一下配置教程

**Comment by jackma66** [comment]
好的，谢谢你。
