### ISSUE TITLE
dd-wrt source code

### ISSUE THREAD

**Issue by ctaoist** [houzi-/dd-wrt-shadowsocks#7]
博主，我装的是你修改过的dd-wrt-r6250的固件，感谢你对dnsmasq的升级和ipset、pdnsd的安装。
我看了一下你的shadowsocks的 `ss-redir+gfwlist` 的实现方法，你是自己写的 `ss-nat` 脚本。
我更喜欢通过 `iptables -t nat -A PREROUTING -p tcp -m set –match-set gfwlist dst -j REDIRECT –to-port 1080` 来实现（网上文章都是这么说的。。。我也觉得简洁一些，**博主试过这种方式吗，有什么经验吗？**）但是iptabels并不支持这个功能，是版本的原因？
我想升级一下iptables，因为涉及到内核，所以就想问下能够要你修改好dnsmasq、ipset和pdnsd的dd-wrt的源码吗？！（我就不改那些部分了，其实是不会。。。）
要是博主可以升级iptables就更好了，作为一个分支啊
ps：我碰巧看到了博主发在mirror/dd-wrt下的issues，成功了吗？

**Comment by houzi-** [comment]
使用方案一就是你所期望的

在 2016年10月10日 下午8:58，275761919 notifications@github.com写道：

**Comment by ctaoist** [comment]
好吧，但是我手动不用脚本，iptables却报错：`Couldn't find match "set"`，卡在了这一步。
手动原因是`/opt`已经装了很多东西

**Comment by houzi-** [comment]
使用我的内置最新版本的iptables 。

```
/usr/iptables/iptables
```

**Comment by ctaoist** [comment]
大神可以问你一个问题吗，输入
`
/usr/iptables/iptables -t nat -A PREROUTING -p tcp -m set --match-set gfw_black_list dst -j REDIRECT --to-port 1080
`
过后 提示：

```
iptables: No chain/target/match by that name
```

这大概是哪里出了问题啊

**Comment by houzi-** [comment]
要加载xt_set模块

**Comment by houzi-** [comment]
然后建立gfw_black_list这个集合

**Comment by ctaoist** [comment]
以前也试过加载xt_set模块，但都提示文件已存在，但今天再重新试一下就突然好了

多谢大神！
