### ISSUE TITLE
Installation reports success but not working

### ISSUE THREAD

**Issue by droogtk** [houzi-/dd-wrt-shadowsocks#8]
root@ddwrt:/opt/etc/init.d# ./S24chinadns start
 Starting chinadns...              failed. 
root@ddwrt:/opt/etc/init.d# chinadns start
Error relocating /opt/bin/chinadns: ns_get32: symbol not found
Error relocating /opt/bin/chinadns: ns_get16: symbol not found

how to fix?

**Comment by houzi-** [comment]
https://github.com/houzi-/dd-wrt-shadowsocks#note
